# Exception handler function

handler(e) ->
  'no worries'


main except handler ->
  true
